name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build and export resume
      run: |
        npx resume-cli export --theme eloquent-mod --format html resume.html
        mkdir public
        mv resume.html public/index.html
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume
        path: public
